# Generated by Django 3.2.7 on 2021-12-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_pharmacy_prod_order_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='pha_review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
