# Generated by Django 3.2.7 on 2021-12-04 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20211202_2037'),
        ('pharmacy', '0004_alter_pharmacy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='user',
            field=models.OneToOneField(blank=True, default='ppp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_register_record', to='doctors.usertype'),
        ),
    ]
