# Generated by Django 3.2.7 on 2021-12-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_pharmacy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
