# Generated by Django 3.2.7 on 2021-12-04 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_alter_pharmacy_user'),
        ('Admin_pharmacy', '0005_auto_20211204_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='pharmacy.pharmacy'),
        ),
    ]
